-- 基线：本站账号与 e 站图集的全部表。
-- 写成幂等的形式：在已有这些表的库上什么也不改，只由迁移器登记为已执行；在空库上则建出同样的结构。
-- drizzle-kit 生成的版本不幂等，这里在它的基础上加了 IF NOT EXISTS，外键按名字查过没有才加；
-- 同目录的 snapshot.json 是 drizzle-kit 1.0 从表结构生成的原样，仍描述同一份结构，后续迁移照常生成。
CREATE TABLE IF NOT EXISTS "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"username" text NOT NULL,
	"password_hash" text NOT NULL,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "eh_credentials" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eh_credentials_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"ipb_member_id" text NOT NULL,
	"ipb_pass_hash" text NOT NULL,
	"igneous" text NOT NULL,
	"has_ex_access" boolean NOT NULL,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "eh_preferences" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eh_preferences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"categories" text[] DEFAULT '{}' NOT NULL,
	"min_rating" integer,
	"reader_interval" integer DEFAULT 5 NOT NULL,
	"search_history" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "eh_preferences_min_rating_check" CHECK ("eh_preferences"."min_rating" BETWEEN 2 AND 5),
	CONSTRAINT "eh_preferences_reader_interval_check" CHECK ("eh_preferences"."reader_interval" BETWEEN 1 AND 20),
	CONSTRAINT "eh_preferences_search_history_check" CHECK (CARDINALITY("eh_preferences"."search_history") <= 10)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "eh_reading_progress" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eh_reading_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"gid" bigint NOT NULL,
	"token" text NOT NULL,
	"page" integer NOT NULL,
	"writer" text NOT NULL,
	"seq" integer NOT NULL,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "eh_tag_translation_syncs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eh_tag_translation_syncs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sha" text NOT NULL,
	"count" integer NOT NULL,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "eh_tag_translations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eh_tag_translations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"namespace" text NOT NULL,
	"raw" text NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$
DECLARE
    foreign_keys CONSTANT text[][] := ARRAY[
        ['eh_credentials', 'eh_credentials_user_id_fkey', 'FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action'],
        ['eh_preferences', 'eh_preferences_user_id_fkey', 'FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action'],
        ['eh_reading_progress', 'eh_reading_progress_user_id_fkey', 'FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action']
    ];
    item text[];
BEGIN
    FOREACH item SLICE 1 IN ARRAY foreign_keys LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conrelid = format('public.%I', item[1])::regclass AND conname = item[2]
        ) THEN
            EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I %s', item[1], item[2], item[3]);
        END IF;
    END LOOP;
END
$$;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "users_username_key" ON "users" USING btree ("username");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "eh_credentials_user_id_key" ON "eh_credentials" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "eh_preferences_user_id_key" ON "eh_preferences" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "eh_reading_progress_user_gid_key" ON "eh_reading_progress" USING btree ("user_id","gid");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "eh_reading_progress_user_recent_idx" ON "eh_reading_progress" USING btree ("user_id","updated_at" DESC NULLS FIRST,"gid" DESC NULLS FIRST);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "eh_tag_translations_namespace_raw_key" ON "eh_tag_translations" USING btree ("namespace","raw");